In [1]:
import pandas as pd

In [6]:
engagement = pd.read_csv('takehome_user_engagement.csv',encoding = "ISO-8859-1")
users = pd.read_csv('takehome_users.csv',encoding = "ISO-8859-1")

In [11]:
engagement.time_stamp = pd.to_datetime(engagement.time_stamp)

In [5]:
users

,object_id,creation_time,name,email,creation_source,last_session_creation_time,opted_in_to_mailing_list,enabled_for_marketing_drip,org_id,invited_by_user_id
0,1,2014-04-22 03:53:30,Clausen August,AugustCClausen@yahoo.com,GUEST_INVITE,1.398139e+09,1,0,11,10803.0
1,2,2013-11-15 03:45:04,Poole Matthew,MatthewPoole@gustr.com,ORG_INVITE,1.396238e+09,0,0,1,316.0
2,3,2013-03-19 23:14:52,Bottrill Mitchell,MitchellBottrill@gustr.com,ORG_INVITE,1.363735e+09,0,0,94,1525.0
3,4,2013-05-21 08:09:28,Clausen Nicklas,NicklasSClausen@yahoo.com,GUEST_INVITE,1.369210e+09,0,0,1,5151.0
4,5,2013-01-17 10:14:20,Raw Grace,GraceRaw@yahoo.com,GUEST_INVITE,1.358850e+09,0,0,193,5240.0
5,6,2013-12-17 03:37:06,Cunha Eduardo,EduardoPereiraCunha@yahoo.com,GUEST_INVITE,1.387424e+09,0,0,197,11241.0
6,7,2012-12-16 13:24:32,Sewell Tyler,TylerSewell@jourrapide.com,SIGNUP,1.356010e+09,0,1,37,NaN
7,8,2013-07-31 05:34:02,Hamilton Danielle,DanielleHamilton@yahoo.com,PERSONAL_PROJECTS,NaN,1,1,74,NaN
8,9,2013-11-05 04:04:24,Amsel Paul,PaulAmsel@hotmail.com,PERSONAL_PROJECTS,NaN,0,0,302,NaN
9,10,2013-01-16 22:08:03,Santos Carla,CarlaFerreiraSantos@gustr.com,ORG_INVITE,1.401833e+09,1,1,318,4143.0
10,11,2013-12-26 03:55:54,Paulsen Malthe,MaltheAPaulsen@gustr.com,SIGNUP,1.388117e+09,0,0,69,NaN
11,12,2014-04-17 23:48:38,Mathiesen Lærke,LaerkeLMathiesen@cuvox.de,ORG_INVITE,NaN,0,0,130,9270.0
12,13,2014-03-30 16:19:38,Fry Alexander,AlexanderDFry@cuvox.de,ORG_INVITE,1.396196e+09,0,0,254,11204.0
13,14,2012-10-11 16:14:33,Rivera Bret,BretKRivera@gmail.com,SIGNUP,1.350058e+09,0,0,0,NaN
14,15,2013-07-16 21:33:54,Theiss Ralf,RalfTheiss@hotmail.com,PERSONAL_PROJECTS,NaN,0,0,175,NaN
15,16,2013-02-11 10:09:50,Engel René,ReneEngel@hotmail.com,PERSONAL_PROJECTS,NaN,0,0,211,NaN
16,17,2014-04-09 14:39:38,Reynolds Anthony,AnthonyReynolds@jourrapide.com,GUEST_INVITE,1.397314e+09,1,0,175,1600.0
17,18,2013-08-24 00:26:46,Gregersen Celina,CelinaAGregersen@jourrapide.com,GUEST_INVITE,NaN,0,0,2,3153.0
18,19,2013-05-24 14:56:36,Collins Arlene,ArleneRCollins@gmail.com,SIGNUP,1.369926e+09,1,0,0,NaN
19,20,2014-03-06 11:46:38,Helms Mikayla,lqyvjilf@uhzdq.com,SIGNUP,1.401364e+09,0,0,58,NaN
20,21,2013-01-22 12:27:42,Hunter Alfie,AlfieHunter@gmail.com,PERSONAL_PROJECTS,1.358858e+09,0,0,54,NaN
21,22,2014-02-10 06:00:46,Myers Jordan,JordanMyers@gmail.com,ORG_INVITE,1.392012e+09,0,0,7,2994.0
22,23,2012-08-17 08:30:27,Souza Alice,AliceAraujoSouza@gustr.com,ORG_INVITE,1.345279e+09,1,0,6,23.0
23,24,2013-09-09 22:20:03,Woodruff James,JamesTWoodruff@cuvox.de,SIGNUP,1.378765e+09,1,0,123,NaN
24,25,2014-02-25 00:11:13,Stone Elise,EliseStone@jourrapide.com,GUEST_INVITE,1.393373e+09,1,0,81,6312.0
25,26,2013-07-28 00:53:32,Wexler Florian,FlorianWexler@jourrapide.com,ORG_INVITE,NaN,0,0,56,11857.0
26,27,2014-01-14 17:35:11,Santos Luís,LuisPintoSantos@gmail.com,ORG_INVITE,1.389807e+09,0,0,134,4189.0
27,28,2013-02-11 20:00:25,Weissmuller Marko,MarkoWeissmuller@jourrapide.com,SIGNUP,1.360872e+09,0,0,6,NaN
28,29,2013-09-16 02:08:41,Fernandes Evelyn,EvelynSousaFernandes@jourrapide.com,SIGNUP,1.379384e+09,0,0,92,NaN
29,30,2013-06-04 00:44:25,Egger Leah,LeahEgger@jourrapide.com,GUEST_INVITE,1.370307e+09,0,0,251,4835.0
...,...,...,...,...,...,...,...,...,...,...
11970,11971,2013-05-04 06:54:23,Ferreira Beatrice,BeatriceBarbosaFerreira@yahoo.com,GUEST_INVITE,NaN,0,0,3,11854.0
11971,11972,2012-09-13 23:23:11,Penington Jamie,JamiePenington@yahoo.com,ORG_INVITE,NaN,0,0,16,7012.0
11972,11973,2012-10-30 03:09:47,Simmons Thomas,ThomasSimmons@gmail.com,PERSONAL_PROJECTS,NaN,0,0,52,NaN
11973,11974,2012-12-26 16:42:08,Scott James,JamesJScott@gmail.com,SIGNUP,1.356713e+09,0,0,167,NaN
11974,11975,2013-03-23 11:10:11,Daecher Jürgen,JurgenDaecher@gustr.com,GUEST_INVITE,1.400757e+09,1,0,31,6410.0
11975,11976,2013-12-25 22:01:41,Kohl Leah,LeahKohl@hotmail.com,PERSONAL_PROJECTS,NaN,0,0,248,NaN
11976,11977,2013-09-17 18:58:51,Crary Joshua,JoshuaHCrary@gmail.com,SIGNUP_GOOGLE_AUTH,1.379704e+09,0,0,144,NaN
11977,11978,2014-04-23 16:28:06,Castro Pedro,PedroCunhaCastro@gustr.com,PERSONAL_PROJECTS,NaN,1,0,29,NaN
11978,11979,2013-01-28 09:26:33,Hurst Harley,HarleyHurst@yahoo.com,SIGNUP,1.359624e+09,0,0,2,NaN
11979,11980,2014-02-02 15:23:18,Gloeckner Franziska,ljnnbqdr@cgbld.com,ORG_INVITE,1.397835e+09,0,0,406,3068.0
11980,11981,2013-03-05 01:53:48,Fry Tyler,TylerFry@gmail.com,GUEST_INVITE,1.364868e+09,0,0,110,5775.0
11981,11982,2013-12-06 14:39:15,Barajas Maria,MariaCBarajas@gmail.com,ORG_INVITE,1.386341e+09,1,1,57,2527.0
11982,11983,2013-07-30 00:23:36,Engel Mike,MikeEngel@gmail.com,SIGNUP_GOOGLE_AUTH,1.375144e+09,0,0,234,NaN
11983,11984,2014-02-11 21:26:11,Reed Cerys,CerysReed@yahoo.com,SIGNUP,1.392154e+09,0,0,170,NaN
11984,11985,2013-07-08 17:23:26,Jespersen Marcus,MarcusTJespersen@cuvox.de,PERSONAL_PROJECTS,NaN,0,0,74,NaN
11985,11986,2012-06-24 01:02:14,Ribeiro Clara,ClaraBarrosRibeiro@gmail.com,SIGNUP_GOOGLE_AUTH,1.341105e+09,0,0,111,NaN
11986,11987,2013-03-15 03:21:01,Reed Poppy,ftdkorrj@uyhoy.com,SIGNUP,1.363318e+09,0,0,1,NaN
11987,11988,2014-03-15 11:04:47,Minick John,JohnFMinick@yahoo.com,PERSONAL_PROJECTS,1.401621e+09,0,0,114,NaN
11988,11989,2013-09-02 11:24:33,Pereira Emilly,EmillyOliveiraPereira@gmail.com,SIGNUP_GOOGLE_AUTH,1.378553e+09,1,0,22,NaN
11989,11990,2013-07-05 21:00:48,Juhl Aase,AasePJuhl@jourrapide.com,ORG_INVITE,1.373144e+09,0,0,25,3944.0
11990,11991,2014-04-20 14:22:45,Vaughn Arthur,ArthurJVaughn@gmail.com,SIGNUP_GOOGLE_AUTH,1.401460e+09,0,0,388,NaN
11991,11992,2014-04-09 19:39:56,Hermansen Amanda,AmandaAHermansen@yahoo.com,PERSONAL_PROJECTS,1.397245e+09,0,0,129,NaN
11992,11993,2013-03-28 23:24:21,Townsend Isabel,IsabelTownsend@cuvox.de,PERSONAL_PROJECTS,NaN,0,0,281,NaN
11993,11994,2012-06-05 04:46:16,Grimstone Joel,conxzghp@eaouk.com,GUEST_INVITE,NaN,0,0,84,5450.0
11994,11995,2013-10-21 13:33:17,Werfel Sebastian,SebastianWerfel@gmail.com,PERSONAL_PROJECTS,1.382449e+09,0,0,0,NaN
11995,11996,2013-09-06 06:14:15,Meier Sophia,SophiaMeier@gustr.com,ORG_INVITE,1.378448e+09,0,0,89,8263.0
11996,11997,2013-01-10 18:28:37,Fisher Amelie,AmelieFisher@gmail.com,SIGNUP_GOOGLE_AUTH,1.358275e+09,0,0,200,NaN
11997,11998,2014-04-27 12:45:16,Haynes Jake,JakeHaynes@cuvox.de,GUEST_INVITE,1.398603e+09,1,1,83,8074.0
11998,11999,2012-05-31 11:55:59,Faber Annett,mhaerzxp@iuxiw.com,PERSONAL_PROJECTS,1.338638e+09,0,0,6,NaN
11999,12000,2014-01-26 08:57:12,Lima Thaís,ThaisMeloLima@hotmail.com,SIGNUP,1.390727e+09,0,1,0,NaN

In [18]:
byday = engagement.groupby(['user_id',pd.Grouper(key='time_stamp',freq='1d')]).agg('count')

In [16]:
byuser = engagement.groupby('user_id').agg('count')

In [ ]:
for user_id in byday:
    if

In [24]:
byday

                    visited
user_id time_stamp
1       2014-04-22        1
2       2013-11-15        1
        2013-11-29        1
        2013-12-09        1
        2013-12-25        1
        2013-12-31        1
        2014-01-08        1
        2014-02-03        1
        2014-02-08        1
        2014-02-09        1
        2014-02-13        1
        2014-02-16        1
        2014-03-09        1
        2014-03-13        1
        2014-03-31        1
3       2013-03-19        1
4       2013-05-22        1
5       2013-01-22        1
6       2013-12-19        1
7       2012-12-20        1
10      2013-01-16        1
        2013-01-22        1
        2013-01-30        1
        2013-02-04        1
        2013-02-06        1
        2013-02-14        1
        2013-02-17        1
        2013-02-19        1
        2013-02-26        1
        2013-03-01        1
...                     ...
11988   2014-04-28        1
        2014-04-29        1
        2014-04-30        1
        2014-05-04        1
        2014-05-08        1
        2014-05-14        1
        2014-05-17        1
        2014-05-18        1
        2014-05-19        1
        2014-05-20        1
        2014-05-21        1
        2014-05-23        1
        2014-05-24        1
        2014-05-26        1
        2014-05-27        1
        2014-06-01        1
11989   2013-09-07        1
11990   2013-07-06        1
11991   2014-04-20        1
        2014-04-25        1
        2014-04-28        1
        2014-05-17        1
        2014-05-30        1
11992   2014-04-11        1
11995   2013-10-22        1
11996   2013-09-06        1
11997   2013-01-15        1
11998   2014-04-27        1
11999   2012-06-02        1
12000   2014-01-26        1

[207917 rows x 1 columns]